const assetList = {
    "register": {
        "images": [
            "./images/registration/bg-extended.webp",
            "./svgs/registration/reg-banner.svg",
            "./svgs/registration/bg-mobile.svg",
            "./svgs/registration/leftarr.svg",
            "./svgs/registration/rightarr.svg",
            "./svgs/registration/dropdown.svg",
            "./svgs/registration/scrollThumb.svg",
            "./svgs/registration/scroll-bar.svg",
            './svgs/registration/back.svg',
            "./images/registration/information.png",
            "./images/registration/info3.png",
        ],
        "videos": []
    },
    "contact": {
        "images": [
            // './images/contact/Aryan.png',
            // './images/contact/Aditya.png',
            // './images/contact/ContactCard2.webp',
            // './images/contact/ContactCard3.webp',
            './images/contact/contact-banner.webp',
            // './images/contact/Ahan.png',
            // './images/contact/Arshita.png',
            // './images/contact/Ayushmaan.png',
            // './images/contact/Dhruv.png',
            // './images/contact/Door1.webp',
            // './images/contact/Door2.webp',
            // './images/contact/Ishita.png',
            // './images/contact/Pranav.png',
            // './images/contact/Rahul.png',
            // './images/contact/SajalY.png',
            './images/contact/ContactCard1.webp',
            './images/contact/DoorsCombined.webp',
            './images/contact/DoorsMobile.webp',
        ],
        "videos": []
    },
    "aboutus": {
        "images": [
            './svgs/aboutus/lines.svg',
            './svgs/aboutus/tree.svg',
            './svgs/aboutus/abt.svg',
            // './svgs/aboutus/dagger.svg',
            // './svgs/aboutus/fan.svg',
            './svgs/aboutus/header.svg',
            // './svgs/aboutus/lantern.svg',
            './svgs/aboutus/letter1.svg',
            './svgs/aboutus/letter2.svg',
            './svgs/aboutus/letter3.svg',
            // './svgs/aboutus/text-frame.svg',
            // './svgs/aboutus/Mask2.svg',
            // './svgs/aboutus/bord.svg',
            './svgs/aboutus/fan.webp',
            './svgs/aboutus/letter4.svg',
            './svgs/aboutus/letter5.svg',
            './svgs/aboutus/letter6.svg',
            './svgs/aboutus/letter7.svg',
            './svgs/aboutus/letter8.svg',
            './svgs/aboutus/next.svg',
            './svgs/aboutus/pause.svg',
            './svgs/aboutus/prev.svg',
            './images/aboutus/background.jpg',
            './images/aboutus/backg.webp',
            './svgs/aboutus/nextarr.svg',
            './svgs/aboutus/play.svg',
            './svgs/aboutus/prvarr.svg',
            './svgs/aboutus/reghead.svg',
            './svgs/aboutus/borde.svg',
            './images/aboutus/abtbck.webp',
        ],
        "videos": []
    },
    "events": {
        "images": [
            './images/events/backg.webp',
            './images/events/dance.webp',
            './images/events/DanceMobile.webp',
            './images/events/down.jpg.png',
            './images/events/drama.webp',
            './images/events/DramaMobile.webp',
            './images/events/evenback.webp',
            './images/events/image.png',
            './images/events/misc.webp',
            './images/events/MiscMobile.webp',
            './images/events/music.webp',
            './images/events/MusicMobile.webp',
            './images/events/photography.webp',
            './images/events/PhotographyMobile.webp',
            './images/events/text.png',
            './images/events/TextMobile.png',
            //  './images/events/quizzes.webp',
            // './images/events/QuizzesMobile.png',
            // './svgs/events/border.svg',
            './svgs/events/bottom.svg',
            './svgs/events/cl1.svg',
            './svgs/events/cl2.svg',
            './svgs/events/dan.webp',
            './svgs/events/eventsback.webp',
            // './svgs/events/Exclude.svg',
            // './svgs/events/Mask.svg',
            // './svgs/events/music.svg',
            './svgs/events/Next1.svg',
            // './svgs/events/Photography.svg',
            './svgs/events/star.svg',
            './svgs/events/star2.svg',
            './svgs/events/text.svg',
            './svgs/events/top.svg',
            './svgs/events/topright.svg',
            "./svgs/events/location.svg",
        ],
        "videos": []
    },
    "gallery": {
        "images": [
            './images/gallery/close_button.png',
            './images/gallery/photog white logo.png',
        ],
        "videos": []
    }
}

export default assetList;