import { cdn } from "./utils/cdn";
const assetList = {
    "register": {
        "images": [
            cdn("/images/registration/bg-extended.webp"),
            cdn("/svgs/registration/reg-banner.svg"),
            cdn("/svgs/registration/bg-mobile.svg"),
            cdn("/svgs/registration/leftarr.svg"),
            cdn("/svgs/registration/rightarr.svg"),
            cdn("/svgs/registration/dropdown.svg"),
            cdn("/svgs/registration/scrollThumb.svg"),
            cdn("/svgs/registration/scroll-bar.svg"),
            cdn('/svgs/registration/back.svg'),
            cdn("/images/registration/information.webp"),
            cdn("/images/registration/info3.webp"),
        ],
        "videos": []
    },
    "contact": {
        "images": [
            // './images/contact/Aryan.png',
            // './images/contact/Aditya.png',
            // './images/contact/ContactCard2.webp',
            // './images/contact/ContactCard3.webp',
            cdn('/images/contact/contact-banner.webp'),
            // './images/contact/Ahan.png',
            // './images/contact/Arshita.png',
            // './images/contact/Ayushmaan.png',
            // './images/contact/Dhruv.png',
            // cdn('/images/contact/Door1.webp'),
            // cdn('/images/contact/Door2.webp'),
            // './images/contact/Ishita.png',
            // './images/contact/Pranav.png',
            // './images/contact/Rahul.png',
            // './images/contact/SajalY.png',
            cdn('/images/contact/ContactCard1.webp'),
            cdn('/images/contact/DoorsCombined.webp'),
            cdn('/images/contact/DoorsMobile.webp'),
        ],
        "videos": []
    },
    "aboutus": {
        "images": [
            // Removed: lines.svg, tree.svg and abt.svg were listed here but have
            // never existed in the repo. Preloader.tsx counts a load as complete
            // only in img.onload -- img.onerror rejects without incrementing --
            // so each missing file permanently held the aboutus percentage below
            // 100. Only Promise.allSettled kept the gate from hanging outright.
            // './svgs/aboutus/dagger.svg',
            // './svgs/aboutus/fan.svg',
            cdn('/svgs/aboutus/header.svg'),
            // './svgs/aboutus/lantern.svg',
            cdn('/svgs/aboutus/letter1.svg'),
            cdn('/svgs/aboutus/letter2.svg'),
            cdn('/svgs/aboutus/letter3.svg'),
            // './svgs/aboutus/text-frame.svg',
            // './svgs/aboutus/Mask2.svg',
            // './svgs/aboutus/bord.svg',
            cdn('/svgs/aboutus/fan.webp'),
            cdn('/svgs/aboutus/letter4.svg'),
            cdn('/svgs/aboutus/letter5.svg'),
            cdn('/svgs/aboutus/letter6.svg'),
            cdn('/svgs/aboutus/letter7.svg'),
            cdn('/svgs/aboutus/letter8.svg'),
            cdn('/svgs/aboutus/next.svg'),
            cdn('/svgs/aboutus/pause.svg'),
            cdn('/svgs/aboutus/prev.svg'),
            cdn('/images/aboutus/background.webp'),
            cdn('/images/aboutus/backg.webp'),
            cdn('/svgs/aboutus/nextarr.svg'),
            cdn('/svgs/aboutus/play.svg'),
            cdn('/svgs/aboutus/prvarr.svg'),
            cdn('/svgs/aboutus/reghead.svg'),
            cdn('/svgs/aboutus/borde.svg'),
            cdn('/images/aboutus/abtbck.webp'),
        ],
        "videos": []
    },
    "events": {
        "images": [
            cdn('/images/events/backg1.webp'),
            cdn('/images/events/Bob.webp'),
            cdn('/images/events/dancef.webp'),
            cdn('/images/events/dramaf.webp'),
            cdn('/images/events/image.webp'),
            cdn('/images/events/misc1.webp'),
            cdn('/images/events/music.webp'),
            cdn('/images/events/music1.webp'),
            cdn('/images/events/musicf.webp'),
            cdn('/images/events/photography.webp'),
            cdn('/images/events/proshow.webp'),
            cdn('/images/events/text.webp'),
            cdn('/images/events/TextMobile.webp'),
            cdn('/images/events/TextMobile1.webp'),
            cdn('/images/events/DramaMobilef.webp'),
            cdn('/images/events/DanceMobilef.webp'),
            cdn('/images/events/MusicMobilef.webp'),
            cdn('/images/events/MiscMobilef.webp'),
            cdn('/images/events/PhotographyMobilef.webp'),
            cdn('/images/events/Eventpics/Agri-Plex.webp'),
            cdn('/images/events/Eventpics/Band_Battle.webp'),
            cdn('/images/events/Eventpics/CADathon.webp'),
            cdn('/images/events/Eventpics/Dedicate_a_song.webp'),
            cdn('/images/events/Eventpics/Fashion_show.webp'),
            cdn('/images/events/Eventpics/Folk_dance.webp'),
            cdn('/images/events/Eventpics/Food_challenge.webp'),
            cdn('/images/events/Eventpics/Fusion_dance.webp'),
            cdn('/images/events/Eventpics/Gully_cricket.webp'),
            cdn('/images/events/Eventpics/Hackathon.webp'),
            cdn('/images/events/Eventpics/Jenga.webp'),
            cdn('/images/events/Eventpics/Life_saver_workshop.webp'),
            cdn('/images/events/Eventpics/Push_up_challenge.webp'),
            cdn('/images/events/Eventpics/Robo-Race.webp'),
            cdn('/images/events/Eventpics/Shoota_and_edit.webp'),
            cdn('/images/events/Eventpics/Solo_and_group_singing.webp'),
            cdn('/images/events/Eventpics/Spot_photography.webp'),
            cdn('/images/events/Eventpics/Stunt_show.webp'),
            cdn('/images/events/Eventpics/Talent_show.webp'),
            cdn('/images/events/Eventpics/Talk_shows.webp'),
            cdn('/images/events/Eventpics/Tech-Exhibition.webp'),
            cdn('/images/events/Eventpics/Traditional_Dressing_competition.webp'),
            cdn('/images/events/Eventpics/Treasure_hunt.webp'),
            cdn('/images/events/Eventpics/Tug_of_war.webp'),
            cdn('/images/events/Eventpics/Water-Rocket-Launch.webp'),
            cdn('/images/events/Eventpics/dj_night.webp'),
            cdn('/svgs/events/bottom.svg'),
            cdn('/svgs/events/cl1.svg'),
            cdn('/svgs/events/cl2.svg'),
            cdn('/svgs/events/dan.webp'),
            cdn('/svgs/events/eventsback.webp'),
            cdn('/svgs/events/Next1.svg'),
            cdn('/svgs/events/star.svg'),
            cdn('/svgs/events/star2.svg'),
            cdn('/svgs/events/text.svg'),
            cdn('/svgs/events/top.svg'),
            cdn('/svgs/events/topright.svg'),
            cdn("/svgs/events/location.svg"),
        ],
        "videos": []
    },
    "gallery": {
        "images": [
            cdn('/images/gallery/close_button.webp'),
            // Removed: 'photog white logo.png' is not in the repo either, and
            // stalled the gallery percentage the same way.
        ],
        "videos": []
    }
}

export default assetList;