// AUTO-GENERATED -- do not edit by hand.
// Regenerate after changing the contents of the asset bucket.
//
// Every entry is a CDN key (see src/utils/cdn.ts). Keys keep the exact directory
// layout the files had under public/; only the origin, and the extension of the
// former PNG/JPEG files, changed.
//
// Totals at generation time: 187 objects, of which 182 are images.

/**
 * Assets that paint on, or just behind, the first screen. index.html carries a
 * matching <link rel="preload"> for each of these, so they are already in flight
 * before React boots and the warm-up below finds them cached.
 *
 * Keep this list and the preload tags in index.html in step -- a preload with no
 * consumer inside a few seconds is a wasted round trip and logs a console warning.
 */
export const CRITICAL_LANDING_ASSETS: readonly string[] = [
  "/images/paper-texture.webp",
  "/videos/ink-spread-4.webp",
  "/svgs/landing/LatestProcessed.svg",
  "/images/logo.webp",
  "/images/hero_hills.webp",
  "/images/hero_mobile.webp",
  "/images/landing/new_tree.webp",
  "/images/landing/tirumala_hills_4k.webp",
  "/images/landing/cloud_1.webp",
  "/svgs/landing/registerBtn.svg",
  "/svgs/landing/mobileRegisterBtn.svg",
  "/svgs/landing/moon1.svg",
  "/svgs/landing/wire.svg",
];

/**
 * Everything else the site can display, in one flat list.
 *
 * The point is that a visitor sitting on the landing page has idle bandwidth, and
 * every page after this one is gated behind a preloader that blocks rendering
 * until its images arrive. Warming the whole catalogue up front turns those gates
 * into no-ops, so /events, /gallery and /aboutus paint instantly instead of
 * counting up from 0%.
 *
 * Audio and video are deliberately excluded -- see HEAVY_MEDIA_ASSETS.
 */
export const DEFERRED_IMAGE_ASSETS: readonly string[] = [
  "/images/aboutus/abtbck.webp",
  "/images/aboutus/backg.webp",
  "/images/aboutus/background.webp",
  "/images/contact/ContactCard1.webp",
  "/images/contact/Door1.webp",
  "/images/contact/Door1Mobile.webp",
  "/images/contact/Door2.webp",
  "/images/contact/Door2Mobile.webp",
  "/images/contact/DoorsCombined.webp",
  "/images/contact/DoorsMobile.webp",
  "/images/contact/contact-banner.webp",
  "/images/doors/Door1.webp",
  "/images/doors/Door2.webp",
  "/images/doors/Door3.webp",
  "/images/doors/Door4.webp",
  "/images/events/Bob.webp",
  "/images/events/DanceMobilef.webp",
  "/images/events/DramaMobilef.webp",
  "/images/events/Eventpics/Agri-Plex.webp",
  "/images/events/Eventpics/Band_Battle.webp",
  "/images/events/Eventpics/CADathon.webp",
  "/images/events/Eventpics/Dedicate_a_song.webp",
  "/images/events/Eventpics/Fashion_show.webp",
  "/images/events/Eventpics/Folk_dance.webp",
  "/images/events/Eventpics/Food_challenge.webp",
  "/images/events/Eventpics/Fusion_dance.webp",
  "/images/events/Eventpics/Gully_cricket.webp",
  "/images/events/Eventpics/Hackathon.webp",
  "/images/events/Eventpics/Jenga.webp",
  "/images/events/Eventpics/Life_saver_workshop.webp",
  "/images/events/Eventpics/Push_up_challenge.webp",
  "/images/events/Eventpics/Robo-Race.webp",
  "/images/events/Eventpics/Shoota_and_edit.webp",
  "/images/events/Eventpics/Solo_and_group_singing.webp",
  "/images/events/Eventpics/Spot_photography.webp",
  "/images/events/Eventpics/Stunt_show.webp",
  "/images/events/Eventpics/Talent_show.webp",
  "/images/events/Eventpics/Talk_shows.webp",
  "/images/events/Eventpics/Tech-Exhibition.webp",
  "/images/events/Eventpics/Traditional_Dressing_competition.webp",
  "/images/events/Eventpics/Treasure_hunt.webp",
  "/images/events/Eventpics/Tug_of_war.webp",
  "/images/events/Eventpics/Water-Rocket-Launch.webp",
  "/images/events/Eventpics/dj_night.webp",
  "/images/events/MiscMobilef.webp",
  "/images/events/MusicMobilef.webp",
  "/images/events/PhotographyMobilef.webp",
  "/images/events/TextMobile.webp",
  "/images/events/TextMobile1.webp",
  "/images/events/backg1.webp",
  "/images/events/dancef.webp",
  "/images/events/dramaf.webp",
  "/images/events/image.webp",
  "/images/events/misc1.webp",
  "/images/events/music.webp",
  "/images/events/music1.webp",
  "/images/events/musicf.webp",
  "/images/events/photography.webp",
  "/images/events/proshow.webp",
  "/images/events/text.webp",
  "/images/gallery/close_button.webp",
  "/images/gallery/gallery1.webp",
  "/images/gallery/gallery2.webp",
  "/images/gallery/gallery3.webp",
  "/images/gallery/gallery4.webp",
  "/images/gallery/gallery5.webp",
  "/images/gallery/gallery6.webp",
  "/images/gallery/kerala-dance.webp",
  "/images/gallery/left-bottom.webp",
  "/images/gallery/left-up.webp",
  "/images/gallery/mm1.webp",
  "/images/gallery/mm2.webp",
  "/images/gallery/mm3.webp",
  "/images/gallery/mm4.webp",
  "/images/gallery/mm5.webp",
  "/images/gallery/mm6.webp",
  "/images/gallery/mm7.webp",
  "/images/gallery/right-bottom.webp",
  "/images/gallery/siv-man-in-action.webp",
  "/images/gallery/students.webp",
  "/images/gallery/top1.webp",
  "/images/landing/MBU.webp",
  "/images/landing/cloud_2.webp",
  "/images/landing/cloud_3.webp",
  "/images/landing/cloud_4.webp",
  "/images/landing/v.webp",
  "/images/mediaPartners/bg1.webp",
  "/images/registration/bg-extended.webp",
  "/images/registration/info3.webp",
  "/images/registration/information.webp",
  "/images/registration/reg-banner.webp",
  "/images/sponsors/Beautiful_Tirupati.webp",
  "/images/sponsors/CS-Overseas.webp",
  "/images/sponsors/ED-West.webp",
  "/images/sponsors/IMFS.webp",
  "/images/sponsors/Mango_Tranquil.webp",
  "/images/sponsors/MayaBazaar.webp",
  "/images/sponsors/Nellorians.webp",
  "/images/sponsors/Sahanah.webp",
  "/images/sponsors/Sneha.webp",
  "/images/sponsors/kalanjali.webp",
  "/svgs/aboutus/abtus.svg",
  "/svgs/aboutus/borde.svg",
  "/svgs/aboutus/fan.webp",
  "/svgs/aboutus/header.svg",
  "/svgs/aboutus/instaicon.svg",
  "/svgs/aboutus/letter1.svg",
  "/svgs/aboutus/letter2.svg",
  "/svgs/aboutus/letter3.svg",
  "/svgs/aboutus/letter4.svg",
  "/svgs/aboutus/letter5.svg",
  "/svgs/aboutus/letter6.svg",
  "/svgs/aboutus/letter7.svg",
  "/svgs/aboutus/letter8.svg",
  "/svgs/aboutus/linkedin.svg",
  "/svgs/aboutus/next.svg",
  "/svgs/aboutus/nextarr.svg",
  "/svgs/aboutus/pause.svg",
  "/svgs/aboutus/play.svg",
  "/svgs/aboutus/prev.svg",
  "/svgs/aboutus/prvarr.svg",
  "/svgs/aboutus/reghead.svg",
  "/svgs/aboutus/xicon.svg",
  "/svgs/aboutus/yticon.svg",
  "/svgs/events/Next1.svg",
  "/svgs/events/bottom.svg",
  "/svgs/events/cl1.svg",
  "/svgs/events/cl2.svg",
  "/svgs/events/dan.webp",
  "/svgs/events/eventsback.webp",
  "/svgs/events/location.svg",
  "/svgs/events/star.svg",
  "/svgs/events/star2.svg",
  "/svgs/events/text.svg",
  "/svgs/events/top.svg",
  "/svgs/events/topright.svg",
  "/svgs/landing/aboutusIcon.svg",
  "/svgs/landing/eventsIcon.svg",
  "/svgs/landing/hamClouds/cloud1.min.svg",
  "/svgs/landing/hamClouds/cloud2.min.svg",
  "/svgs/landing/hamClouds/cloud3.min.svg",
  "/svgs/landing/hamClouds/cloud4.min.svg",
  "/svgs/landing/hamClouds/cloud5.min.svg",
  "/svgs/landing/hamClouds/cloud6.min.svg",
  "/svgs/landing/hamX.svg",
  "/svgs/landing/homeIcon.svg",
  "/svgs/landing/insta.svg",
  "/svgs/landing/instaLamp.svg",
  "/svgs/landing/mobileBackground.svg",
  "/svgs/landing/moonHam.svg",
  "/svgs/landing/phone.svg",
  "/svgs/landing/youtube.svg",
  "/svgs/landing/youtubeLamp.svg",
  "/svgs/mediaPartners/mediaHead.svg",
  "/svgs/registration/back.svg",
  "/svgs/registration/bg-extended.svg",
  "/svgs/registration/bg-mobile.svg",
  "/svgs/registration/button-banner.svg",
  "/svgs/registration/dropdown.svg",
  "/svgs/registration/field2.svg",
  "/svgs/registration/leftarr.svg",
  "/svgs/registration/list-tag.svg",
  "/svgs/registration/reg-banner.svg",
  "/svgs/registration/rightarr.svg",
  "/svgs/registration/scroll-bar.svg",
  "/svgs/registration/scrollThumb.svg",
  "/svgs/registration/signin.svg",
  "/svgs/sponsors/sponsorsHead.webp",
  "/videos/ink-spread-5.gif",
];

/** CRITICAL_LANDING_ASSETS + DEFERRED_IMAGE_ASSETS. */
export const ALL_IMAGE_ASSETS: readonly string[] = [
  ...CRITICAL_LANDING_ASSETS,
  ...DEFERRED_IMAGE_ASSETS,
];

/**
 * Audio and the gallery showreel: 25.4 MB between them, none of it needed to
 * render a page. Left to stream on demand rather than warmed, so the warm-up
 * never competes with the visible page for bandwidth.
 */
export const HEAVY_MEDIA_ASSETS: readonly string[] = [
  "/sounds/Shape_of_U_x_Carnatic.mp3",
  "/sounds/bg-music.mp3",
  "/sounds/bg-music2.mp3",
  "/sounds/door-close.mp3",
  "/videos/1_Glimpse_of_MM2k23.mp4",
];
