const assetList = {
    "register": {
        "images": [
            "./images/registration/bg-extended.png",
            "./svgs/registration/reg-banner.svg",
            "./svgs/registration/bg-mobile.svg",
            "./svgs/registration/leftarr.svg",
            "./svgs/registration/rightarr.svg",
            "./svgs/registration/dropdown.svg",
            "./svgs/registration/scrollThumb.svg",
            "./svgs/registration/scroll-bar.svg",
            './svgs/registration/back.svg',
            "./images/registration/information.png",
            "./images/registration/info3.png",
        ],
        "videos": []
    },
    "contact": {
        "images": [
            // './images/contact/Aryan.png',
            './images/contact/Aditya.png',
            // './images/contact/ContactCard2.png',
            // './images/contact/ContactCard3.png',
            './images/contact/contact-banner.png',
            // './images/contact/Ahan.png',
            './images/contact/Arshita.png',
            './images/contact/Ayushmaan.png',
            './images/contact/Dhruv.png',
            // './images/contact/Door1.png',
            // './images/contact/Door2.png',
            './images/contact/Ishita.png',
            './images/contact/Pranav.png',
            './images/contact/Rahul.png',
            './images/contact/SajalY.png',
            './images/contact/ContactCard1.png',
            './images/contact/DoorsCombined.png',
            './images/contact/DoorsMobile.png',
        ],
        "videos": []
    },
    "aboutus": {
        "images": [
            './svgs/aboutus/lines.svg',
            './svgs/aboutus/tree.svg',
            './svgs/aboutus/abt.svg',
            // './svgs/aboutus/dagger.svg',
            // './svgs/aboutus/fan.svg',
            './svgs/aboutus/header.svg',
            // './svgs/aboutus/lantern.svg',
            './svgs/aboutus/letter1.svg',
            './svgs/aboutus/letter2.svg',
            './svgs/aboutus/letter3.svg',
            // './svgs/aboutus/text-frame.svg',
            // './svgs/aboutus/Mask2.svg',
            // './svgs/aboutus/bord.svg',
            './svgs/aboutus/fan.png',
            './svgs/aboutus/letter4.svg',
            './svgs/aboutus/letter5.svg',
            './svgs/aboutus/letter6.svg',
            './svgs/aboutus/letter7.svg',
            './svgs/aboutus/letter8.svg',
            './svgs/aboutus/next.svg',
            './svgs/aboutus/pause.svg',
            './svgs/aboutus/prev.svg',
            './images/aboutus/background.jpg',
            './images/aboutus/backg.png',
            './svgs/aboutus/nextarr.svg',
            './svgs/aboutus/play.svg',
            './svgs/aboutus/prvarr.svg',
            './svgs/aboutus/reghead.svg',
            './svgs/aboutus/borde.svg',
            './images/aboutus/abtbck.png',
        ],
        "videos": []
    },
    "events": {
        "images": [
            './images/events/backg.png',
            './images/events/dance.png',
            './images/events/DanceMobile.png',
            './images/events/down.jpg.png',
            './images/events/drama.png',
            './images/events/DramaMobile.png',
            './images/events/evenback.png',
            './images/events/image.png',
            './images/events/misc.png',
            './images/events/MiscMobile.png',
            './images/events/music.png',
            './images/events/MusicMobile.png',
            './images/events/photography.png',
            './images/events/PhotographyMobile.png',
            './images/events/text.png',
            './images/events/TextMobile.png',
            //  './images/events/quizzes.png',
            // './images/events/QuizzesMobile.png',
            // './svgs/events/border.svg',
            './svgs/events/bottom.svg',
            './svgs/events/cl1.svg',
            './svgs/events/cl2.svg',
            './svgs/events/dan.svg',
            './svgs/events/eventsback.svg',
            // './svgs/events/Exclude.svg',
            // './svgs/events/Mask.svg',
            // './svgs/events/music.svg',
            './svgs/events/Next1.svg',
            // './svgs/events/Photography.svg',
            './svgs/events/star.svg',
            './svgs/events/star2.svg',
            './svgs/events/text.svg',
            './svgs/events/top.svg',
            './svgs/events/topright.svg',
            "./svgs/events/location.svg",
            "./svgs/events/oasis_logo.svg",
        ],
        "videos": []
    },
    "gallery": {
        "images": [
            './images/gallery/close_button.png',
            './images/gallery/photog white logo.png',
            // './images/gallery/photog black logo.png',
        ],
        "videos": []
    },
    "sponsors": {
        "images": [
            '/images/sponsors/EaseMyTrip.png',
            '/images/sponsors/Nutribs.png',
            '/images/sponsors/Qoneqt.png',
            '/images/sponsors/Snapchat.png',
            '/images/sponsors/Suno.png',
            '/images/sponsors/abhibus.png',
            '/images/sponsors/rtc.jpg',
            '/images/sponsors/Zebronics.avif',
            '/images/sponsors/artisbaazi.png',
            '/images/sponsors/coke.png',
            '/images/sponsors/gustora.webp',
            '/images/sponsors/hdfc.png',
            '/images/sponsors/jio-saavn.png',
            '/images/sponsors/maa-karni.jpg',
            '/images/sponsors/netApp.png',
            '/images/sponsors/pee-safe.png',
            '/images/sponsors/pepero.jpeg',
            '/images/sponsors/plum-body-lovin.png',
            '/images/sponsors/plum-goodness.png',
            '/images/sponsors/posterwa.png',
            '/images/sponsors/travelzada.jpeg',
        ],
        "videos": []
    },
    "mediaPartners": {
        "images": [
            '/images/mediaPartners/Bronx.png',
            '/images/mediaPartners/Captures.png',
            '/images/mediaPartners/Jhoom.jpg',
            '/images/mediaPartners/Kanika.png',
            '/images/mediaPartners/Sarcaaster.png',
            '/images/mediaPartners/Zack.jpeg',
            '/images/mediaPartners/bg.jpg',
            '/images/mediaPartners/bg1.jpg',
        ],
        "videos": []
    }
}

export default assetList;